name: Collect Plugin Artifacts

on:
  push:
    branches:
      - main

jobs:
  collect-artifacts:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "src"

      # デバッグ: どんなファイルがあるか確認
      - name: List all files
        run: |
          echo "Listing all files under src:"
          find $GITHUB_WORKSPACE/src -type f

      # artifacts フォルダに既存の zip と updater.json を集める
      - name: Collect existing artifacts
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts
          find $GITHUB_WORKSPACE/src -name "*.zip" -exec cp {} $GITHUB_WORKSPACE/artifacts/ \;
          find $GITHUB_WORKSPACE/src -name "updater.json" -exec cp {} $GITHUB_WORKSPACE/artifacts/ \;

      # artifacts をアップロード
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: $GITHUB_WORKSPACE/artifacts
